services:
  # postgresql 
  resturants-hub-db:
    container_name: resturants-hub
    hostname:  ${DATABASE_HOST}
    image: postgres:16-alpine
    networks:
      - backend
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: on-failure
  dbgate:
    container_name: db-gate
    image: dbgate/dbgate
    restart: always
    ports:
      - 81:3000
    volumes:
      - dbgate-data:/root/.dbgate
    networks:
      - backend
    environment:
      CONNECTIONS: pg
      LABEL_pg: restaurants-hub
      SERVER_pg: resturants-hub
      USER_pg: ${POSTGRES_USER}
      PASSWORD_pg: ${POSTGRES_PASSWORD}
      PORT_pg: ${DB_PORT}
      ENGINE_pg: postgres@dbgate-plugin-postgres

volumes:
  dbgate-data:
    driver: local

networks:
  backend:
    driver: bridge
