version: "3.7"
services:

  # postgresql 
  resturants-hub-db:
    container_name: resturants-hub
    hostname: postgresql
    image: postgres:12-alpine
    networks:
      - backend
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: on-failure

networks:
  backend:
    driver: bridge
